spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pizza_hut_rh
    username: mohamed
    password: Alt22032022!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082
